### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by C-Ll-l** [ZhenrongShen/CellGAN#2]
Thank you for your research, which can be great. May I ask if the dataset for the paper can be found? And what can be the minimum number of experimental datasets? How much does the number of cell images within the dataset affect the experiment?

**Comment by ZhenrongShen** [comment]
Thank you for your interest! 

The dataset used in our experiment is currently private and cannot be shared at this time. Although no experiments have been conducted on public data, we believe that our method can work on other datasets.

The number of cell images can indeed affect the experiment's outcomes. As illustrated in Section 3 of our paper (https://arxiv.org/abs/2307.06182), a larger number of training images generally lead to better image quality as well as higher FID, and vice versa. As for the minimum number of experimental datasets, it can vary depending on your specific criterion for image quality or effectiveness in the downstream tasks.
